plugins { id 'com.android.application' }

android {
    namespace 'com.yad.videodl'
    compileSdk 34

    defaultConfig {
        applicationId "com.yad.videodl"
        minSdk 24
        targetSdk 34
        versionCode 13
        versionName "13.0.0"
        ndk { abiFilters 'arm64-v8a', 'armeabi-v7a' }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                'META-INF/DEPENDENCIES',
                'META-INF/LICENSE',
                'META-INF/LICENSE.txt',
                'META-INF/NOTICE',
                'META-INF/NOTICE.txt',
                'META-INF/INDEX.LIST',
                'META-INF/*.kotlin_module'
            ]
        }
        // FIX: exclude libc++_shared.so yang duplikat dari opencv
        jniLibs {
            useLegacyPackaging = true
            pickFirsts += [
                'lib/**/libc++_shared.so',
                'lib/**/libc++_shared.so'
            ]
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    // FFmpeg untuk hapus watermark
    implementation 'com.antonkarpenko:ffmpeg-kit-full-gpl:2.1.0'

    // OpenCV untuk image recognition
    implementation 'com.quickbirdstudios:opencv:4.5.3.0'
}
